volumes:
  postgres_data:
  minio_data:

services:
  delivery_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: delivery_server
    depends_on:
      postgres_demo_db:
        condition: service_healthy
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_demo_db:5432/delivery
      DELIVERY_MINIO_URL: http://minio:9000
      DELIVERY_MINIO_UNAME: minioadmin
      DELIVERY_MINIO_PASS: minioadmin
      DELIVERY_MINIO_BUCKET: delivery

  postgres_demo_db:
    image: bitnami/postgresql
    container_name: postgres_server
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=delivery
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    healthcheck:
      test: [ "CMD", "curl", "-k", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./minio_data:/data
    command: server /minio_data/data --console-address :9001
